### ISSUE TITLE
A bug in aws-java-sdk 1.10.34

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/aws-scala-tools#32]
The current stable release is based on aws-java-sdk 1.10.34. (see 1e17b4cbda455b564c45834faf7fb7a4d4c711fc) 
And here is what happens in runtime every time when a S3/EC2 client is created:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at com.amazonaws.internal.config.InternalConfig.<clinit>(InternalConfig.java:43)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:95)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:53)
	at com.amazonaws.services.ec2.AmazonEC2Client.<init>(AmazonEC2Client.java:153)
	at ohnosequences.awstools.ec2.EC2$.create(EC2.scala:361)
...
```

We need to downgrade to 1.10.32 (which doesn't have such problem) and release M2.

A relevant issue: https://github.com/aws/aws-sdk-java/issues/555

**Comment by laughedelic** [comment]
I'm going to update to 1.10.35. Closing this

**Comment by goldenrat** [comment]
I still see the issue in 1.0.37 version.

**Comment by laughedelic** [comment]
@goldenrat I have discovered, that in the project where I encountered this issue, I had some `dependencyOverrides` with old versions of jackson and the minimum required version in aws-sdk-java is jackson-2.5.3. Since I removed that thing I don't have the problem anymore. If it's not the case for you, you should probably write here: https://github.com/aws/aws-sdk-java/issues/555
